export const initialGridData = [
  {
    id: 0,
    type: "image",
    videoType: "none",
    initialPhoto: "/Media/y1_bumsan.jpg",
    clue: "A photo of ice cream (from an ice cream shop).",
    pageClue: "Take a photo of ice cream from an ice cream shop.",
    description: "Every time you visited LA this year, the first part of every itinerary I created was figuring out when to stop by Bumsan. There is an irreplicable joy from that vanilla matcha swirl in your hand (even with the mandatory complaint about getting rid of their corn flakes) that even I can’t compete with, so I’m honored to have merely played a part in getting your fix. Ice cream has been a part of you and your family’s DNA for so long that it would be dishonest to characterize it as exclusive to us, but you’ve incorporated me into a shared appreciation for this dessert that makes me just as grateful to have tried so many great new flavors with you, as I am to have seen that irreplaceable smile so many times this year.",
    confirmation: "Nice ice cream!",
    letter: "C",
    photo: null, 
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 1,
    type: "video",
    videoType: "horizontal",
    initialPhoto: "/Media/y1_recording.mp4",
    clue: "A photo of a gacha item.",
    pageClue: "Take a photo of any gacha item you've won.",
    description: "For someone who claims luck isn’t on your side, your success rate with gachapon this year was uncharacteristically impressive. I would consider it skill the way you manifest the exact item you desire (usually after the second or third attempt). The fact that a majority of our visits were for your siblings is really sweet, and is a direct reflection of how much you truly care for them and how often you think of them on a day-to-day basis. You got me hooked too; I really can’t resist seeing this kind of reaction out of you.",
    confirmation: "Nice gacha!",
    letter: "A",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 2,
    type: "image",
    videoType: "none",
    initialPhoto: "/Media/y1_scrabble.jpg",
    clue: "A photo of a board game.",
    pageClue: "",
    description: "",
    confirmation: "Nice board game!",
    letter: "L",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 3,
    type: "video",
    videoType: "vertical",
    initialPhoto: "/Media/y1_fit.mp4",
    clue: "A photo of your fit.",
    description: "",
    confirmation: "Nice fit!",
    letter: "L",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 4,
    type: "image",
    videoType: "none",
    initialPhoto: "/Media/y1_skincare.jpg",
    clue: "A photo of a skincare product.",
    pageClue: "",
    description: "",
    confirmation: "Nice skincare!",
    letter: "L",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
];