export const initialGridData = [
  {
    id: 0,
    type: "image",
    videoType: "none",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_bumsan.jpg",
    clue: "A photo of ice cream.",
    pageClue: "Take a photo of any ice cream you like.",
    description: "Every time you visited LA this year, the first part of every itinerary I created was figuring out when to stop by Bumsan. There is an irreplicable joy from that vanilla matcha swirl in your hand (even with the mandatory complaint about getting rid of their corn flakes) that even I can’t compete with, so I’m honored to have merely played a part in getting your fix. Ice cream has been a part of you and your family’s DNA for so long that it would be dishonest to characterize it as exclusive to us, but you’ve incorporated me into a shared appreciation for this dessert that makes me just as grateful to have tried so many great new flavors with you, as I am to have seen that irreplaceable smile so many times this year.",
    confirmation: "Nice ice cream!",
    letter: "D",
    photo: null, 
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
    howTo: true,
  },
  {
    id: 1,
    type: "video",
    videoType: "horizontal",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_recording.mp4",
    clue: "A photo of a ukelele.",
    pageClue: "Take a photo of a ukelele.",
    description: "Allowing me the chance to see and work together with you on the songs you want to bring to life has been some of the most investing and rewarding experiences this year by far. You have become such an expressive, intelligent and creative songwriter, and I’m so proud of you, not only for the phenomenal writing streak you were on this year, but for the growth and grasp you’ve had on your artistic vision that has made working together on your music seamless and fulfilling. I know we’re both newer to working music DAWs, and we haven’t gotten as many songs started on as we wanted to, but I am both very optimistic and very eager to knock these demos out this year. I promise to continue to try my absolute hardest to serve your musical ideas to the best of my ability.",
    confirmation: "Nice ukelele!",
    letter: "I",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 2,
    type: "video",
    videoType: "vertical",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_gacha.mp4",
    clue: "A photo of a gacha item.",
    pageClue: "Take a photo of a gacha item you've won.",
    description: "For someone who claims luck isn’t on your side, your success rate with gachapon this year was uncharacteristically impressive. I would consider it skill the way you manifest the exact item you desire (usually after the second or third attempt). The fact that a majority of our visits were for your siblings is also really sweet, and is a direct reflection of how much you truly care for them. You got me hooked too; I can’t lie how fun it is to pick out which gachapon we want to win together and test our luck. I also really can’t resist seeing these incredibly cute reactions out of you.",
    confirmation: "Nice gachapon!",
    letter: "G",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 3,
    type: "image",
    videoType: "none",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_festival.jpg",
    clue: "A photo of any item/merch of an artist you've seen live.",
    pageClue: "Take a photo of any item or merch of an artist you've seen live in concert.",
    description: "It’s an amusing thought now that, for the past three years and up until halfway through the year, I’d never had the chance to experience live music at a concert or festival with you. Considering the latter half of this year was spent wildly correcting this imbalance, I can now safely report that attending concerts and festivals with you is truly enjoyable and enhancing in every way imaginable to me. Of all the live music events to reflect on, HITC holds a special spot in my heart, not just because it was our first, or because I finally got to live my dream of seeing Porter Robinson live. From the moment you found out what city I lived in three years ago, you set fate on its course by telling me how you always wanted to go to HITC. There was a moment during the 2NE1 set that I thought to myself how unreal it was that I was actually there with you, following up on distant plans made years ago, as more than friends. I think it’s kind of poetic.",
    confirmation: "Nice merch!",
    letter: "I",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 4,
    type: "video",
    videoType: "vertical",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_clubbing.mp4",
    clue: "A photo at a bar/club.",
    pageClue: "Take a photo at any bar/club.",
    description: "You’re really good at taking something I already enjoy, and making it so that I enjoy it so much more with you to the point that I don’t want to do it unless you’re there with me. Going out with you is maybe the best example of this I can think of. I can confidently say that I’ve never enjoyed going to bars, clubs, house parties more than I have this year with you by my side, to get me to dance with you, to order more Jameson than I ever thought I would, to help talk to other girls for our friends to fumble. For whatever dance floor we find ourselves on, it’s cliche but you really do feel like the only person in the room. It’s a feeling that really can’t be replicated, so I think you’re just going to have to be there with me every time I go out from now on, and vice-versa.",
    confirmation: "Nice bar/club pic!",
    letter: "T",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 5,
    type: "image",
    videoType: "none",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_scrabble.jpg",
    clue: "A photo of a Scrabble board.",
    pageClue: "Take a photo of a Scrabble board.",
    description: "I don’t know if you really have a chance of beating me at Scrabble anytime soon, but I will admit you have been improving at an alarmingly high rate each time we’ve played this year. It’s been over ten years since I’ve played Scrabble with my uncle, and playing with you this year made me realize just how much I missed it. I see just how much of an effort you always make to share and try the things I love, and I’m so immensely grateful that you always want to do that for me. So thank you for reinvigorating my love for things I’ve lost touch with myself, especially board games.",
    confirmation: "Nice Scrabble board!",
    letter: "A",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 6,
    type: "image",
    videoType: "none",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_food.jpg",
    clue: "A photo of food you cooked/prepared.",
    pageClue: "Take a photo of any food that you cooked or prepared.",
    description: "We really know how to spoil ourselves. I’ll take a larger share of the blame between the two of us for how much we’ve dined finely this year, but it does always go back to the fact that we genuinely work so well because of our mutual affinity and appreciation for good food. I love that you get just as excited as I do to try new restaurants on my never-ending to-visit list, I love that you’ve greatly expanded my admiration for cuisines and dishes that I probably wouldn’t have pushed myself to try without you, I love how often you indulge me on my cravings even when you know I probably shouldn’t be indulged, and I love how you’ve reinvigorated my desire to cook again, not just Trader Joe’s frozen food. There’s nothing that can quell your love for food, and I hope that never, ever changes. I mean just look at how happy you are with your KBBQ.",
    confirmation: "Nice food!",
    letter: "L",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 7,
    type: "video",
    videoType: "vertical",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_fit.mp4",
    clue: "A photo of your fit.",
    pageClue: "Take a photo of your fit.",
    description: "You know how adamant I am on the fact that your fashion is refined talent and one of your greatest assets. Over the course of our time together this year, you have put together the most stunning, creative, occasion-perfect outfits that continually amaze me. It’s been such a blessing being with you in LA by mere virtue of having more occasions for you to dress up. I’m honored to be your full-time photographer and videographer (and part-time guest) for your curated feed that I’m very excited for you to continue posting. The world deserves to continue to see your talent as much as I have this year.",
    confirmation: "Nice fit!",
    letter: "C",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 8,
    type: "image",
    videoType: "none",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_friends.jpg",
    clue: "A photo of a photo booth strip.",
    pageClue: "Take a photo of any photo booth strip.",
    description: "I know we both spent a lot of this year integrating more into our respective social atmospheres, but moving to LA meant a greater emphasis placed on building a foundation within my own community. You didn’t have to, but it makes me feel so tremendously fortunate and grateful to see how much you’ve embraced and respected the people I care about so much in my life. It’s a mutual appreciation that has been reflected back to me so often, it’s funny to sometimes ponder whether you’re closer to some of my friends than I am at this point. Thank you for treating my family, my friends with esteem and appreciation, for showing them some of the same sides of yourself that I love you so much for, and for putting up with all of the jokes that stem from no one having ever visited Wisconsin before.",
    confirmation: "Nice photo booth pictures!",
    letter: "A",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 9,
    type: "video",
    videoType: "horizontal",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_workshop.mp4",
    clue: "A photo of a ring.",
    pageClue: "Take a photo of a ring on your finger.",
    description: "As you’ve probably picked up on by now, I love a good artistic workshop or class to do together on our dates. It gives me a perfect excuse to learn a new skill I have no business learning on my own, and gives you another way to demonstrate how well your innate artistic creativity applies to everything. I can’t come up with a less cliche way to express the fact that you always make me want to try new things and put myself out of my usual scope of life solely because of you, how rewarding the thought is of figuring them out together with you. I hope we never run out of different classes or workshops to sign up for, since I do have a good number of Safari tabs and Instagram videos saved that we could definitely continue to check out this year if you’re as down as I am.",
    confirmation: "Nice ring!",
    letter: "M",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 10,
    type: "image",
    videoType: "none",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_skincare.jpg",
    clue: "A photo of a skincare product.",
    pageClue: "Take a photo of a skincare product that you like.",
    description: "You’ve introduced me to a lot of new worlds this year, and shown me in many ways how much I don’t know. While you certainly seem to enjoy humbling me most of the chances you have, I really appreciate everything that I’ve picked up and learned from you. It’s a good indication of mutual openness and growth to acquire each other’s skills over time, and we seem to be on that track. For one, my skin barrier has never been healthier after remodeling my skincare routine and product lineup from your expertise. Even though it’s only been half a year since you’ve moved on from Ulta, I’m beholden to have learned so much from my very own in-house skincare specialist. I always love to see you own what you know.",
    confirmation: "Nice skincare!",
    letter: "E",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 11,
    type: "image",
    videoType: "none",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_coffee.jpg",
    clue: "A photo of coffee.",
    pageClue: "Take a photo of a coffee drink you bought.",
    description: "Coffee is such a paradox for us. On one hand, I know how much you disapprove of my excessive coffee consumption (and spending) under the guise of needing caffeine and a space away from home to get work done. On the other hand, I would describe our mutual desire and enthusiasm for exploring all of the amazing coffee shops in both Los Angeles and the Midwest as one of our love languages of sorts. The fact that your Instagram feed receives more posts about coffee shop openings than mine now at this point indicates just how much you care about always making sure that I have an iced latte in my hands, no matter where we are. Thank you for always looking for the cutest cafes to go and try, for encouraging me the most to finish my coffee shop website, and for prioritizing something so much for me simply because you know how much I enjoy it. To be known is to be loved.",
    confirmation: "Nice coffee!",
    letter: "R",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
  {
    id: 12,
    type: "video",
    videoType: "vertical",
    initialPhoto: process.env.PUBLIC_URL + "/Media/y1_music.mp4",
    clue: "A photo of wired earbuds.",
    pageClue: "Take a photo of any wired earbuds or headphones.",
    description: "In the first couple of weeks that we were getting to know each other in Korea, you often like to mention that it was my unbridled enthusiasm for listening to and talking about music that really opened your perception of me, gave us a strong commonality to bond over, and laid the groundwork for our plans to go to a particular music festival sometime. It’s maybe not that much of a stretch to say that music is one of the main reasons I can call you mine today. I’m happy to report that this year, I’ve listened to and shared so much incredible music with you that will be attached to some of the greatest memories of a lifetime. Even though you now understand where I took the idea of using an audio splitter from, I’m pleased that it’s now become a thing of ours. I can’t wait to listen to so many more albums in this lifetime with you. Sorry for putting your lip syncing on blast in case anyone else sees this website and scrolls down this far, but at least I didn’t use the video with the original video.",
    confirmation: "Nice wired earbuds/headphones!",
    letter: "A",
    photo: null,
    isRevealed: false,
    revealToggle: false,
    revealClue: false,
  },
];